# Global settings applied to the whole site.  
# 
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).


# Settings in the [build] context are global and are applied to all contexts 
# unless otherwise overridden by more specific contexts.  
[build]
  base = ""
  publish = "/public"
  command = "gatsby build"


# Production context: All deploys to the main
# repository branch will inherit these settings.
# [context.development]
#   command = "make production"
#   [context.production.environment]
#     ACCESS_TOKEN = "super secret"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
# [context.deploy-preview.environment]
#   NOSCRAPE = "true"

# Branch deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
# [context.branch-deploy]
#   command = "make staging"

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.develop]
  base = ""
  command = "gatsby build"